### PR TITLE
Add an additional read after reading a block to ensure eof is set correctly

### LINKED ISSUE #9: The lib breaks for streams that do not implement getSize()
While this all works great with filesystem streams, streams that are not are failing. One such example is https://github.com/violet-php/streaming-json-encoder which cannot tell what the resulting stream size could be (otherwise that would defeat the whole purpose of it).

The issue happens in `AesEncryptingStream::encryptBlock() `on line 114; where the `getSize()` of the underlying stream returns null (and null is a valid return value as per PSR7).

Quick removal of lines 112 through 117 solves the issue, but the tests were made on small data sets.

### LINKED ISSUE #10: Padding is not always removed from last block
When decrypting a stream. The `eof()` method is used to determine if the block should use `OPENSSL_ZERO_PADDING` or not for the decryption.

https://github.com/jeskew/php-encrypted-streams/blob/master/src/AesDecryptingStream.php#L102

The code essentially says that the logical or should only be applied if it is not the last block in the stream/file. This is if either the `eof()` is false or if the stream size does not equal the current pointer position.

However, `eof` is not reliable to determine if this is the last block or not. It will only return true if you have read past the end of the file. Not if you are at the end of the file. See https://www.php.net/manual/en/function.feof.php#67261

For example, when passing in a `$length` which is exactly the amount that is left to be read in the stream, `eof()` will return false even though all of the data has been read and the stream is at the end. You're required to do an additional `read()` in order to set `eof` correctly.

Subsequently, this means the returned `$plainText` contains the padding characters because they were not removed by `openssl` when the decryption takes place (as it has been disabled by the logical or).

### PR DESCRIPTION
**Pull request by jackbentley**
Padding is not always removed from the last block - see #10 

This MR adds an additional `read()` to ensure the `eof()` is set correctly on the stream/file. The result of the `read()` is stored in a buffer in case it's not empty and can then be used on the next read of the stream.

Fixes #9
Fixes #10

### CODE REVIEW

**Comment by jeskew** [comment]
I've been having trouble writing a test case for the issue reported and think this is best solved by just removing the `$this->stream->getSize() !== $this->stream->tell()` check from both `AesEncryptingStream` and `AesDecryptingStream`. 

Could you take a look at #13 and let me know if it would solve #10 ?

**Comment by jackbentley** [comment]
I added an additional test case to the PHPUnit suite for the issue. I think it's correct in what it's testing. See https://github.com/jeskew/php-encrypted-streams/pull/11/files#diff-7f9ac45d88f6a32191c083986270fd5bR158-R182

Unfortunately, #13 doesn't solve #10 and the test in this branch still fails in #13.

To re-hash what the actual issue is... the cypher method requires padding, so we need to know if we are at the last block in order to remove the padding. However, if you only `->read()` the exact stream length, the code never knows to remove the padding. This is because `->eof()` only returns true when you're *after* the end of the stream - not *at* it. 

From what you wrote in #13, I think the additional check you added for the `->getSize()` of the stream intends to fix this. However, there's a bug in it. I think it should be an `&&` and not an `||`. Changing it to an `&&` causes my additional test to pass. However, this is then not fixing #9.

**Comment by jeskew** [comment]
Thanks for the detailed explanation! I didn't realize the bug was that decryption streams would convert additional padding into space characters. I incorporated your work into #13 but moved the test case into the existing provider function and updated how `cipherBuffer` is populated so that it's either empty or contains a single 16-byte block (to minimize additional reads from the underlying stream when filling the function-local `cipherText` buffer variable).

**Comment by jackbentley** [comment]
Closed in favour of #13

**Pull request closed without merging**
